---
title: "Drosophila mauritiana - Copynumber analysis"
output: rmarkdown::github_document
editor_options: 
  markdown: 
    wrap: sentence
    author: Riccardo
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
suppressPackageStartupMessages(library(tidyverse))
suppressPackageStartupMessages(library(knitr))
suppressPackageStartupMessages(library(kableExtra))
theme_set(theme_bw())

knitr::opts_knit$set(root.dir = "/Volumes/Temp1/simulans-old-strains/analysis/plots")
```

## Dmel library (+ Gypsy7 and Gypsy29 from Dsim)

```{r}
analysis <- function(csv, old, new) {
  
copynumbers <- read_csv(csv, show_col_types = FALSE) %>% filter(Sample!="Sample") %>% type_convert() %>% mutate(age = ifelse(Sample %in% old, "old", "new"))

avg_museum_modern <- copynumbers %>% group_by(age, TE) %>% summarise(All_reads=mean(All_reads))
museum <- avg_museum_modern %>% filter(age == "old") %>% ungroup() %>% select(TE, All_reads) %>% rename(old_cn = All_reads)
modern <- avg_museum_modern %>% filter(age == "new") %>% ungroup() %>% select(TE, All_reads) %>% rename(new_cn = All_reads)
fold <- inner_join(museum, modern, by="TE") %>% type_convert() %>% mutate(fold_enrichment = new_cn/old_cn) %>% filter(new_cn > 2)

plot_fold <- ggplot(data = fold, aes(x = TE, y = fold_enrichment)) +
  geom_bar(stat = "identity", position = "dodge", aes(fill = fold_enrichment > 2)) +
  scale_fill_manual(values = c("FALSE" = "gray", "TRUE" = "red")) +
  xlab("TE") +
  ylab("fold enrichment") +
  theme(legend.position = "none", axis.title.x = element_blank(), axis.text.x = element_blank()) +
  geom_text(aes(label = ifelse(fold_enrichment > 2, as.character(TE), "")), 
            position = position_dodge(width = 1),
            vjust = -0.5, size = 3, angle=90)+
  ggtitle("Old vs Modern - All reads")

fold_enriched <- fold %>% filter(fold_enrichment>2) %>% arrange(desc(fold_enrichment))

comparison_foldenriched <- copynumbers %>% ungroup() %>% select(-HQ_reads, -age) %>% pivot_wider(names_from = Sample, values_from = All_reads) %>% filter(TE %in% fold_enriched$TE)# %>% inner_join(fold_enriched, by="fold_enrichment")

list(plot = plot_fold, table = fold_enriched, each_sample = comparison_foldenriched)
}
```

```{r}
old_mau <- c("SRR6425993","SRR19973828")
new_mau <- c("SRR1560097","SRR1560268","SRR1560103")
```

```{r}
dmel_TEs <- analysis("/Volumes/Temp1/simulans-old-strains/analysis/csv/Dmau/dmel_TEs/Dmau-dmel_TEs.csv", old_mau, new_mau)
dmel_TEs$plot
kable(dmel_TEs$table)
kable(dmel_TEs$each_sample)
```

## Clark library

```{r}
clark <- analysis("/Volumes/Temp1/simulans-old-strains/analysis/csv/Dmau/clark/Dmau-clark.csv", old_mau, new_mau)
clark$plot
kable(clark$table)
kable(clark$each_sample)
```


## Chakraboty library

```{r}
chak <- analysis("/Volumes/Temp1/simulans-old-strains/analysis/csv/Dmau/chakraboty/Dmau-chak.csv", old_mau, new_mau)
chak$plot
kable(chak$table)
kable(chak$each_sample)
```

