---
title: "Drosophila melanogaster - Copynumber analysis"
output: rmarkdown::github_document
editor_options: 
  markdown: 
    wrap: sentence
    author: Riccardo
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
suppressPackageStartupMessages(library(tidyverse))
suppressPackageStartupMessages(library(knitr))
suppressPackageStartupMessages(library(kableExtra))
suppressPackageStartupMessages(library(ggpubr))
theme_set(theme_bw())

knitr::opts_knit$set(root.dir = "/Volumes/Temp1/simulans-old-strains/analysis/plots")
```

```{r}
analysis <- function(csv, old, new, year, titlee) {
  
copynumbers <- read_csv(csv, show_col_types = FALSE) %>% filter(Sample!="Sample", Sample%in%c(old, new)) %>% type_convert() %>% mutate(age = ifelse(Sample %in% old, "old", "new")) %>% inner_join(year, by="Sample") %>% arrange(collection_year) %>% mutate(Sample = paste0(Sample, "_", collection_year)) %>% select(-collection_year)

avg_museum_modern <- copynumbers %>% group_by(age, TE) %>% summarise(All_reads=mean(All_reads))
museum <- avg_museum_modern %>% filter(age == "old") %>% ungroup() %>% select(TE, All_reads) %>% rename(old_cn = All_reads)
modern <- avg_museum_modern %>% filter(age == "new") %>% ungroup() %>% select(TE, All_reads) %>% rename(new_cn = All_reads)
fold <- inner_join(museum, modern, by="TE") %>% type_convert() %>% mutate(fold_enrichment = new_cn/old_cn) %>% filter(new_cn > 2)

plot_fold <- ggplot(data = fold, aes(x = TE, y = fold_enrichment)) +
  geom_bar(stat = "identity", position = "dodge", aes(fill = fold_enrichment > 2)) +
  scale_fill_manual(values = c("FALSE" = "gray", "TRUE" = "red")) +
  xlab("TE") +
  ylab("fold enrichment") +
  theme(legend.position = "none", axis.title.x = element_blank(), axis.text.x = element_blank()) +
  geom_text(aes(label = ifelse(fold_enrichment > 2, as.character(TE), "")), 
            position = position_dodge(width = 1),
            vjust = -0.5, size = 3, angle=90)+
  ggtitle(titlee)

fold_enriched <- fold %>% filter(fold_enrichment>2) %>% arrange(desc(fold_enrichment))

comparison_foldenriched <- copynumbers %>% ungroup() %>% select(-HQ_reads, -age) %>% pivot_wider(names_from = Sample, values_from = All_reads) %>% filter(TE %in% fold_enriched$TE)# %>% inner_join(fold_enriched, by="fold_enrichment")

list(plot = plot_fold, table = fold_enriched, each_sample = comparison_foldenriched)
}
```

```{r}
timeline <- function(csv, age, transposon) {
  single_te <- read_csv(csv, show_col_types = FALSE) %>% filter(Sample!="Sample") %>% type_convert() %>% filter(TE==transposon) %>% inner_join(age, by="Sample") %>% arrange(collection_year)
  
  plot <- ggplot(single_te, aes(x = reorder(Sample, collection_year), y = HQ_reads)) +
    geom_point(size = 1.5) +
    scale_x_discrete(labels = single_te$collection_year) +
    labs(y = "copynumber", x = "collection_year") + ggtitle(transposon)
}
```

```{r}
samples <- c("SRR23876563", "SRR23876564", "SRR23876562", "SRR23876569", "SRR23876586", "SRR11846555", "SRR11846565", "SRR11846559", "SRR9951090") 
years <- c(1800, 1800, 1850, 1850, 1933, 1936, 1958, 1987, 2015)
age_dmel <- tibble(collection_year = years, Sample = samples)

pre1900 <- c("SRR6425993","SRR19973828","SRR23876562","SRR23876569")
pre1950 <- c("SRR23876586","SRR11846555","SRR11846565")
modern <- c("SRR11846559","SRR9951090")
```

## Dmel library (+ Gypsy7 and Gypsy29 from Dsim)

```{r}
dmel_TEs <- analysis("/Volumes/Temp1/simulans-old-strains/analysis/csv/Dmel/Dmel-TEs/Dmel-dmel_TEs.csv", pre1900, modern, age_dmel, "Pre-1900 vs Post-1980")
dmel_TEs$plot
kable(dmel_TEs$table)
kable(dmel_TEs$each_sample)

dmel_TEs <- analysis("/Volumes/Temp1/simulans-old-strains/analysis/csv/Dmel/Dmel-TEs/Dmel-dmel_TEs.csv", pre1900, pre1950, age_dmel, "Pre-1900 vs Pre-1980")
dmel_TEs$plot
kable(dmel_TEs$table)
kable(dmel_TEs$each_sample)

dmel_TEs <- analysis("/Volumes/Temp1/simulans-old-strains/analysis/csv/Dmel/Dmel-TEs/Dmel-dmel_TEs.csv", pre1950, modern, age_dmel, "Pre-1980 vs Post-1980")
dmel_TEs$plot
kable(dmel_TEs$table)
kable(dmel_TEs$each_sample)
```

```{r}
candidates <- c("412", "BLOOD", "DMHFL1", "DMIFACA", "OPUS", "PPI251", "TIRANT", "gypsy-7-dsim")

for (t in candidates){
 dmel_TEs_timeline <- timeline("/Volumes/Temp1/simulans-old-strains/analysis/csv/Dmel/Dmel-TEs/Dmel-dmel_TEs.csv", age_dmel, t)
  print(dmel_TEs_timeline)
}
```


## Clark library

```{r}
clark <- analysis("/Volumes/Temp1/simulans-old-strains/analysis/csv/Dmel/clark/Dmel-clark.csv", pre1900, modern, age_dmel, "Pre-1900 vs Post-1980")
clark$plot
kable(clark$table)
kable(clark$each_sample)

clark <- analysis("/Volumes/Temp1/simulans-old-strains/analysis/csv/Dmel/clark/Dmel-clark.csv", pre1900, pre1950, age_dmel, "Pre-1900 vs Pre-1980")
clark$plot
kable(clark$table)
kable(clark$each_sample)

clark <- analysis("/Volumes/Temp1/simulans-old-strains/analysis/csv/Dmel/clark/Dmel-clark.csv", pre1950, modern, age_dmel, "Pre-1980 vs Post-1980")
clark$plot
kable(clark$table)
kable(clark$each_sample)
```

```{r}
candidates <- c("412", "blood", "hobo", "I-element", "NOF", "Nomad", "family-999_gypsy", "family-325_gypsy", "gypsy6", "gypsy8", "gypsy12", "BEL", "FB")

for (t in candidates){
 clark_timeline <- timeline("/Volumes/Temp1/simulans-old-strains/analysis/csv/Dmel/clark/Dmel-clark.csv", age_dmel, t)
  print(clark_timeline)
}
```